spring:
  cloud:
    stream:
      function:
        definition: orderSupplier;productEventConsumer
      bindings:
        orderSupplier-out-0:
          destination: order-event

        productEventConsumer-in-0:
          destination: product-event