spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      function:
        definition: orderSupplier;productEventConsumer
      bindings:
        orderSupplier-out-0:
          destination: order-event

        productEventConsumer-in-0:
          destination: product-event