spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      function:
        definition: orderEventProcessor
      bindings:
        orderEventProcessor-in-0:
          destination: order-event
        orderEventProcessor-out-0:
          destination: product-event